default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: battleship_react_development

test:
  <<: *default
  database: battleship_react_test

production:
  <<: *default
  database: battleship_react_production
  username: battleship_react
  password: <%= ENV['BATTLESHIP_REACT_DATABASE_PASSWORD'] %>
